# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
        ('jury', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CS', 'College Student'), ('HS', 'High School')], default='CS', max_length=2)),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('field_of_study', models.TextField(blank=True)),
                ('college_year', models.IntegerField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jury.Jury')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='term.Term')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='university.University')),
            ],
        ),
    ]
