# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juries', to='term.Term')),
            ],
            options={
                'verbose_name_plural': 'Juries',
            },
        ),
    ]
