# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('prez_fr', models.CharField(max_length=100, null=True)),
                ('prez_tw', models.CharField(max_length=100, null=True)),
                ('prez_sg', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
